#!/bin/bash

#C# $(mysql_db_list)
#C# $(mysql_table_list ${A_PARAMS[CINDEX-1]})
#C--# --prefix=_test_

tb_getopt db_name table= - $@

if [ -e ~/etc/mysql/localhost/passwd ]
then
  mysqldump  -u$(id -u -n)  -p$(cat ~/etc/mysql/localhost/passwd) --no-data $db_name $table | sed -e '/^\/\*!/d' -e '/^--/d' -e 's%EXISTS `%EXISTS `'$prefix'%g' -e 's%TABLE `%TABLE `'$prefix'%g'
elif [ -e ~/.my.cnf ]
then
  mysqldump  -u$(id -u -n) --no-data $db_name $table | sed -e '/^\/\*!/d' -e '/^--/d' -e 's%EXISTS `%EXISTS `'$prefix'%g' -e 's%TABLE `%TABLE `'$prefix'%g'
fi


return 0