#!/bin/bash

apt install -y curl wget tree htop gnupg2 ca-certificates lsb-release debian-archive-keyring net-tools software-properties-common readline-common pv

tb_getopt timezone=Europe/Paris locale=en_US.UTF-8 - $@

timedatectl set-timezone $timezone

sed -i "/$locale UTF-8/d" /etc/locale.gen
echo $locale UTF-8 >>/etc/locale.gen
update-locale LANG=$locale LANGUAGE=$locale LC_ALL=$locale

dpkg-reconfigure --frontend=noninteractive locales

date
