#!/bin/bash
#C# --last

if [ "$last" == "on" ]; then
  apt install apt-transport-https curl -y

  source /etc/os-release

  mkdir -p /etc/apt/keyrings
  curl -o /etc/apt/keyrings/mariadb-keyring.pgp 'https://mariadb.org/mariadb_release_signing_key.pgp'

  if [ "$ID" == "Ubuntu" ]; then
    echo "
      X-Repolib-Name: MariaDB
      Types: deb
      URIs: https://mirror.mva-n.net/mariadb/repo/11.4/ubuntu
      Suites: $VERSION_CODENAME
      Components: main main/debug
      Signed-By: /etc/apt/keyrings/mariadb-keyring.pgp
    " >/etc/apt/sources.list.d/mariadb.list
  else
    echo "
        deb [signed-by=/etc/apt/keyrings/mariadb-keyring.pgp] https://mirror.mva-n.net/mariadb/repo/11.4/debian $VERSION_CODENAME main
      " >/etc/apt/sources.list.d/mariadb.list
  fi

  apt update -y
fi

apt install -y mariadb-server

tb mysql sudo/install/root --force
