#!/bin/bash
#C# --last

if [ "$last" == "on" ]; then
  apt install apt-transport-https curl -y

  source /etc/os-release

  mkdir -p /etc/apt/keyrings
  curl -o /etc/apt/keyrings/mariadb-keyring.pgp 'https://mariadb.org/mariadb_release_signing_key.pgp'

  if [ "$ID" == "ubuntu" ]; then
    echo "
deb [signed-by=/etc/apt/keyrings/mariadb-keyring.pgp] https://deb.mariadb.org/11.4/ubuntu $VERSION_CODENAME main
    " >/etc/apt/sources.list.d/mariadb.list
  else
    echo "
deb [signed-by=/etc/apt/keyrings/mariadb-keyring.pgp] https://mirror.mva-n.net/mariadb/repo/11.4/debian $VERSION_CODENAME main
      " >/etc/apt/sources.list.d/mariadb.list
  fi

  apt update -y
fi

apt install -y mariadb-server

[ ! -f /root/.my.cnf ] && tb mysql sudo/install/root --force
