#!/bin/bash
curl  https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar > /usr/local/bin/wp
chmod +x /usr/local/bin/wp

echoc -g2 wp-cli installed to /usr/local/bin/wp
echo 
echoc -g1 su user 
echoc -g1 cd
echoc -g1 cd app/webroot 
echoc -g1 wp search-replace foo bar
echo