#!/bin/bash

function max
{
	if [ $1 -eq $2 ]
	then
		echo $1
	else
		if [ $1 -gt $2 ]
		then
			echo $1
		else
			echo $2
		fi
	fi

	return 0
}

function max_of
{
	local i max

	max=$1; shift

	for i in $@
	do
		max=$(max $max $i)
	done

	echo $max
}

