#!/bin/bash

function md5
{
	echo $@ | md5sum | sed 's%  -$%%g'

	return 0
}

function str_to_lower
{
	echo $1 | tr "[:upper:]" "[:lower:]"

	return 0
}

function str_to_upper
{
	echo $1 | tr "[:lower:]" "[:upper:]"

	return 0
}

function gen_urandom_passwd 
{
	size=${1-24}


	head -c 500 /dev/urandom | tr -dc a-z0-9A-Z | head -c $size; echo

	return 0
}

function gen_mac
{
	local mac separator

	separator=${1-:}

	mac=$(head -c 500 /dev/urandom | tr -dc 0-9A-F | head -c 12; echo)

 	for ((i=0;i<12;i=i+1))
	do
		echo -n ${mac:$i:1}
		[[ $((i%2)) = 1 && $i != 11 ]] && echo -n $separator
	done

	echo

	return 0
}


function gen_apg_passwd
{
	apg -a 0 -M NCL -n 1 -x 8 -m 10 -x 10

	return 0
}
