#!/bin/bash
#!/bin/bash

function mysql_query {
	local db_user db_passwd file d_home db_host_to db_port the_port

	# 	[ -z "$SQL" ] && return 0

	[[ "$@" =~ ^.*-h\ ?([a-z0-9.]*).* ]] && db_host_to=${BASH_REMATCH[1]}

	[ -z "$db_host_to" ] && db_host_to=localhost

	db_user=$(id -u -n)

	d_home=$(grep ^$db_user: /etc/passwd | awk -F[:] '{print $6}')

	f_port=$d_home/etc/mysql/$db_host_to/port
	if [ -e $f_port ]; then
		db_port=$(cat $f_port)
	fi

	if [[ $db_host_to != "localhost" && -z "$db_port" ]]; then
		db_port=4231
	fi

	[ -n "$db_port" ] && the_port="-P $db_port"

	f_cnf=$d_home/.my.cnf

	if [ -e $f_cnf ]; then
		if [ -n "$SQL" ]; then
			echo "$SQL" | mysql -B -u$db_user -h$db_host_to -s $the_port $@
		else
			mysql -B -u$db_user -h$db_host_to -s $the_port $@ <&0
		fi
	else
		echoc -y1 "$f_passwd unexistant !"
	fi

	return 0
}

function mysql_user_list {
	local SQL
	SQL="SELECT CONCAT(user,'@',host) FROM user;"

	if [ -n "$db_host_to" ]; then
		the_host="-h $db_host_to"
	fi

	mysql_query mysql $the_host | sed -e '/^root@localhost$\|^debian-sys-maint@localhost$/d'

	return 0
}

function mysql_db_list {
	local SQL

	SQL="SHOW DATABASES;"

	if [ -n "$db_host_to" ]; then
		the_host="-h $db_host_to"
	fi

	mysql_query mysql $the_host | sed -e '/^mysql$\|^information_schema$\|^performance_schema$\|^sys$\|lost+found/d'

	return 0
}

function mysql_table_list {
	local SQL

	SQL="SELECT TABLE_NAME FROM TABLES WHERE TABLE_SCHEMA='$1';"

	if [ -n "$db_host_to" ]; then
		the_host="-h $db_host_to"
	fi

	mysql_query information_schema $the_host

	return 0
}

return 0
