#!/bin/bash

#C# All $(app_list) $(tb mysql sudo/db/list)
#C# All db app

tb_getopt app=All type=All - $@


date=$(date +'%y-%m-%d-%HH%M')
d_sav1=/var/sav1/$(hostname)
mkdir -p $d_sav1/{auto,system}


if [ "$app" = All ]
then
	for i in $(find $d_sav1/auto -maxdepth 1 -mindepth 1 -type d | sort | tac | sed '25,$!d')
	do
		rm -rf $i
	done

	for i in $(find $d_sav1/system -maxdepth 1 -mindepth 1 -type d | sort | tac | sed '20,$!d')
	do
		rm -rf $i
	done


	date
	echo "############## SYSTEM ############## "

	for i in etc root; 
	do 
		dir=$d_sav1/system/$date
		echo "############## $dir/$i ##############"; 
		mkdir -p $dir
		
		tar cjf $dir/$i.tar.bz2 -C /$i . |true; done
	echo

	date
	echo "############## MYSQL ##############"
	for i in $(tb mysql sudo/db/list)
	do
		[ $i == performance_schema ] && continue
		[ $i == information_schema ] && continue
		
		dir=$d_sav1/auto/$date/$i
		echo "############## $dir"
		mkdir -p $dir
	
		tb mysql sudo/db/dump $i | bzip2 > $dir/$i.sql.bz2
	done
	echo

	date
	echo "############## APPs ##############"
	for i in $(app_list)
	do
		dir=$d_sav1/auto/$date/$i
		
		echo "############## $dir"

		
		mkdir -p $dir	
		tar cjf $dir/$i.tar.bz2 -C /apps/$i .
	done
	date
	for i in $(app_list) $(tb mysql sudo/db/list)
	do
		du -sh $d_sav1/auto/$date/$i
	done
	date
	echo
else
	dir=$d_sav1/manual/$app/$date
	mkdir -p $dir

	
	if [[ "$type" = "All" || "$type" = "app" ]]
	then
		echo "############## MANUAL $app APP $dir/$app.tar.bz2"
		tar cjf $dir/$app.tar.bz2 -C /apps/$app .
	fi
	
	if [[ "$type" = "All" || "$type" = "db" ]]
	then
		echo "############## MANUAL $app DB $dir/$app.sql.bz2"
		tb mysql sudo/db/dump $app | bzip2 > $dir/$app.sql.bz2
	fi
	
	echo "############## Done"

fi

