#!/bin/bash

#C# All $(app_list)
#C# $(find /usr/bin/ -name "php*.*"| sed 's%/usr/bin/php%%')
#C--# --certbot	--webdomain= --www --remove --template=pma --template=joomla --noconfdb --noconfwebserver --noconfphpfppm --wildcard

mode=$(cat /conf/mode)

tb app sudo/way/$mode/create $@

