#!/bin/bash

#C# apache nginx hybrid proxy
#C# 7.3 7.4 8.0 8.1
#H# mode php email webdomain

tb_getopt mode email webdomain php=7.4  - $@

mkdir -p /conf 
mkdir -p /apps


echo $mode > /conf/mode
echo $php > /conf/php
echo $email > /conf/email
echo $webdomain > /conf/webdomain

